name: 'unauth'
services:
  api:
    container_name: 'unauth'
    image: 'ghcr.io/shba007/unauth-api:latest'
    restart: on-failure:3
    # build: .
    # volumes:
    #     - type: bind
    #       source: $(pwd)/image-name/static
    #       target: /app/static
    #       readonly:
    env_file:
      - .env.prod
    ports:
      - 2210:3000
